### ISSUE TITLE
datasets problem

### ISSUE THREAD

**Issue by LinjieFu-U** [ZAX130/RDP#1]
Hello, can you provide the processed datasets

**Comment by ZAX130** [comment]
I'm so sorry that I'm afraid I can't, because the size of the total dataset is too big. However, we have further published the link of the IXI dataset processed by freesurfer and an example code of how to create a pkl dataset from the original dataset, which may help with this issue.

**Comment by ZAX130** [comment]
We have published the pkl-format LPBA dataset we used in experiments.

**Comment by LinjieFu-U** [comment]
Thank you very much for your contributions. We were able to reproduce results similar to those in your work on both IXI and LPBA datasets, but when we tried to use the data in the link of Mindboggle dataset you provided for the experiment, the DICE of the experiment result was only 0.49, far lower than the result of 0.62 in your work. We suspect that it is a problem when we process the data. Could you please provide the processed Mindboggle dataset?

**Comment by ZAX130** [comment]
Have you ever tried to change the Seg_norm() in data/trans.py and dice_val_VOI in utils.py?

**Comment by LinjieFu-U** [comment]
Yes, we used the seg_norm() and dice_val Settings for the OASIS dataset in Transmorph

**Comment by ZAX130** [comment]
But you need to change them according to the labels in Mindboggle. You can print all the classes in the label data.

**Comment by LinjieFu-U** [comment]
Sorry to bother you, but I have another question. How should I calculate the dice of each region separately as in the paper.

**Comment by ZAX130** [comment]
Please check the code in FAIM: https://github.com/dykuang/Medical-image-registration/blob/master/source/view_dice.py
