### ISSUE TITLE
How to Get 31 ROIs of IXI dataset

### ISSUE THREAD

**Issue by bingcheg** [ZAX130/RDP#10]
Dear author,

First of all, thank you for your excellent work. I want to reproduce the resutls of the IXI datset with 31 ROIs as you mentioned in your paper. I have downloaded the preprocessed IXI dataset from the link you provided and I find there is 35 ROIs existed in the label.nii. 

My question is that which 31 ROIs do you used for registration evaulation? 

Best !

**Comment by ZAX130** [comment]
Thank you for your question. To align with the 31 ROIs used in our evaluation, please update the seg_table in Seg_norm as follows:

```
self.seg_table = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 
                           16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])
```
This accounts for the fact that some labels in the IXI dataset are not shared across all data.

Please let me know if you need any further assistance!

Best regards,
Haiqiao Wang

**Comment by bingcheg** [comment]
Thank you for your reply.
Another relevent question is regarding the data split, how do you define which 407 subjects as training set and 58 as testing set. 

I follow the split method in transmorph, and it looks like has 403 for training and 58 for val.

**Comment by bingcheg** [comment]
Also, if you could help me to identity which seven ROIS you mention in your paper as :" Fig. 5. Box plots showing the distributions of DSC scores of seven regions on the LPBA dataset produced by different registration methods."  

Can you please tell me the number of those seven ROIs and their corresponding brain area :"
self.seg_table = np.array([0, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 61, 62,
               63, 64, 65, 66, 67, 68, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 101, 102, 121, 122, 161, 162,
               163, 164, 165, 166])"

**Comment by ZAX130** [comment]
check&nbsp;https://github.com/dykuang/Medical-image-registration/blob/master/source%2Fview_dice.py



---Original---
From: "Bingchen ***@***.***&gt;
Date: Fri, Dec 6, 2024 18:17 PM
To: ***@***.***&gt;;
Cc: "Haiqiao ***@***.******@***.***&gt;;
Subject: Re: [ZAX130/RDP] How to Get 31 ROIs of IXI dataset (Issue #10)




 
Also, if you could help me to identity which seven ROIS you mention in your paper as :" Fig. 5. Box plots showing the distributions of DSC scores of seven regions on the LPBA dataset produced by different registration methods."
 
Can you please tell me the number of those seven ROIs and their corresponding brain area :"
 self.seg_table = np.array([0, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 61, 62,
 63, 64, 65, 66, 67, 68, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 101, 102, 121, 122, 161, 162,
 163, 164, 165, 166])"

**Comment by bingcheg** [comment]
Great, how about data split in IXI dataset?

**Comment by ZAX130** [comment]
We shuffled the preprocessed IXI dataset provided by FreeSurfer and selected 407 cases for training and 58 cases for testing. The link to the IXI dataset processed by FreeSurfer can be found on the project homepage.



---Original---
From: "Bingchen ***@***.***&gt;
Date: Fri, Dec 6, 2024 18:47 PM
To: ***@***.***&gt;;
Cc: "Haiqiao ***@***.******@***.***&gt;;
Subject: Re: [ZAX130/RDP] How to Get 31 ROIs of IXI dataset (Issue #10)




 
Great, how about data split in IXI dataset?

**Comment by bingcheg** [comment]
Dear author, 

Thanks for replying me. I have tried to replace the esg_table to self.seg_table = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 
                           16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]) >
                        
                        
 However, the DSC results for the IXI dataset is around 0.49 only, I wonder is this is due to the dataset choice for the test? 
 
 
 Best!

**Comment by bingcheg** [comment]
I further think is this due to the image below?
![图片_20241209092339](https://github.com/user-attachments/assets/8be0f8e8-259c-4fcb-9481-f40637d24ec0)

**Comment by bingcheg** [comment]
By the way, how do you calcualte the ASSD and HD95 metrics in your paper, I did not find the corresponding calcualtion metrics in the code

**Comment by ZAX130** [comment]
Regarding how to change the dataset to run the code, you can now see the relevant instructions on the homepage.
![image](https://github.com/user-attachments/assets/2ab1dc8a-8e29-4250-b173-b68f55cee3d5)

For the calculation of ASSD and HD95, you can learn about the usage of MedPy.

**Comment by bingcheg** [comment]
Dear Author, 

Thank you for replying me. just for the ASSD and HD95, i utilized the ASSD and HD95 as image below, but I found that the score for ASSD is around:"Deformed ASSD: 0.918 +- 0.086
Deformed HD95: 3.740 +- 0.383"
![image](https://github.com/user-attachments/assets/54a3f0ef-946a-4233-818a-a91de012a1a5)
which is relatively smaller than the results in your paper, can you please let me know how do you use the ASSD and HD95?

**Comment by ZAX130** [comment]
I use a for loop to calculate the metrics on each VOI separately, then calculate the average.



---Original---
From: "Bingchen ***@***.***&gt;
Date: Mon, Dec 9, 2024 16:11 PM
To: ***@***.***&gt;;
Cc: "Haiqiao ***@***.******@***.***&gt;;
Subject: Re: [ZAX130/RDP] How to Get 31 ROIs of IXI dataset (Issue #10)




 
Dear Author,
 
Thank you for replying me. just for the ASSD and HD95, i utilized the ASSD and HD95 as image below, but I found that the score for ASSD is around:"Deformed ASSD: 0.918 +- 0.086
 Deformed HD95: 3.740 +- 0.383"
 image.png (view on web)
 which is relatively smaller than the results in your paper, can you please let me know how do you use the ASSD and HD95?

**Comment by bingcheg** [comment]
Dear author,

I have downloaded the IXI processed dataest from your link. and I wonder how do you achieve this process mentioned in your paper"
![image](https://github.com/user-attachments/assets/381b244a-e01c-479d-bdd1-699bc141e645)
"

thank you

**Comment by bingcheg** [comment]
to be specific, I mean the resize process.

**Comment by ZAX130** [comment]
You can check how to use SimpleITK to resample nii files based on spacing.&nbsp;



---Original---
From: "Bingchen ***@***.***&gt;
Date: Tue, Dec 24, 2024 12:06 PM
To: ***@***.***&gt;;
Cc: "Haiqiao ***@***.******@***.***&gt;;
Subject: Re: [ZAX130/RDP] How to Get 31 ROIs of IXI dataset (Issue #10)




 
to be specific, I mean the resize process.

**Comment by Pull2MAX** [comment]
这个是modet的assd回答，你看看。
[每个类别的ASSD值](https://github.com/ZAX130/SmileCode/issues/11#issuecomment-2351364340)
