### ISSUE TITLE
关于LPBA40数据集

### ISSUE THREAD

**Issue by Wusibei** [ZAX130/RDP#11]
您好！我想了解一下您使用的LPBA40数据集，根据您的文章引用[52]中的链接无法获取数据集，根据README中的链接，找到多个LPBA40数据集，请问您使用的哪一个，希望能够复现您这一部分的内容，恳切期望得到您的回复。

**Comment by ZAX130** [comment]
![image](https://github.com/user-attachments/assets/624843a1-bba9-4eba-a7ae-f51d47078599)
这个

**Comment by ZAX130** [comment]
您也可以用我们主页上预处理好的LPBA数据集
