### ISSUE TITLE
Mindboggle数据集

### ISSUE THREAD

**Issue by githublizhipan** [ZAX130/RDP#3]

**Comment by ZAX130** [comment]
你可以看看我代码里lpba数据集制作过程，它们差不多。



---原始邮件---
发件人: "Leo ***@***.***&gt;
发送时间: 2024年5月23日(周四) 下午2:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZAX130/RDP] Mindboggle数据集 (Issue #3)




 
您好，想请问一下Mindboggle数据集需要做哪些预处理工作？我拿到的Mindboggle是(182, 218, 182)，请问您是使用什么工具进行裁剪的？裁剪后需要做归一化吗？感谢🙇‍

**Comment by githublizhipan** [comment]
好的，感谢




plumwillclimb
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZAX130/RDP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月23日(星期四) 晚上11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZAX130/RDP] Mindboggle数据集 (Issue #3)





 你可以看看我代码里lpba数据集制作过程，它们差不多。 
 
 
 
 ---原始邮件--- 
 发件人: "Leo ***@***.***&amp;gt; 
 发送时间: 2024年5月23日(周四) 下午2:09 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [ZAX130/RDP] Mindboggle数据集 (Issue #3) 
 
 
 
 
   
 您好，想请问一下Mindboggle数据集需要做哪些预处理工作？我拿到的Mindboggle是(182, 218, 182)，请问您是使用什么工具进行裁剪的？裁剪后需要做归一化吗？感谢🙇‍
