### ISSUE TITLE
Mindboggle101数据集以及标签问题

### ISSUE THREAD

**Issue by 5ummer23** [ZAX130/RDP#6]
尊敬的作者您好，打扰您了，感谢您提供了Mindboggle数据集，有两个问题想请教您
1.Mindboggle数据集我第一次使用，请问您是用的哪个压缩包作为图片，哪个作为标签？
![wenti1](https://github.com/ZAX130/RDP/assets/144659587/8530f82a-ae41-41bc-ae59-ea5625cafe01)

2.关于dice_val_VOI中标签不匹配的问题
想请问原VOI_lbls中有一些标签值与数据集标签值中有些对不上，这样是否会影响到dice的平均值，我能否改成与seg_table中相匹配的标签值
![image](https://github.com/ZAX130/RDP/assets/144659587/1502364f-281d-4fa4-bc18-17e1708fda15)
![image](https://github.com/ZAX130/RDP/assets/144659587/5f3e0baf-62b5-4e3f-a78c-1bcba49d13ca)

**Comment by ZAX130** [comment]
https://github.com/ZAX130/SmileCode/issues/9
