### ISSUE TITLE
关于使用mindboggle101训练集

### ISSUE THREAD

**Issue by 0305sherrynan** [ZAX130/RDP#9]
您好！请问一下想复现您用mindboggle101数据集的那部分，除了修改seg_norm()和dice_val_VOI()的标签值，还需要做其他什么改动吗？
另外想请问一下是用数据集中的哪两个文件分别作为图像数据和标签的。感谢大佬的贡献！
![image](https://github.com/user-attachments/assets/c0d0398c-d281-4474-b28e-55758b4a8069)

**Comment by ZAX130** [comment]
非常感谢您的关注，首先修改标签值只需要修改Seg_norm()和dice_val_VOI()，其次我们使用的Mindboggle数据集分为两组设定，仿射与未仿射的。仿射设定下我们采用的t1weighted_brain.MNI152.nii.gz和labels.DKT31.manual.MNI152.nii.gz，未仿射设定下我们采用的t1weighted_brain.nii.gz和labels.DKT31.manual.nii.gz
